beyondcode/laravel-self-diagnosis

- src/Checks/ComposerIsUpToDate.php
I am one of those strange people that has `composer.phar` in the root of my project instead of relying upon composer being globally installed. `Illuminate\Support\Composer` has support for this in `findComposer()` but it needs to know the workingDirectory. I am not sure how you feel about calling functions like `base_path()` in your code but this did fix the issue for me
> Find composer when not globally installed

- src/Checks/AppKeyIsSet.php
- src/Checks/CorrectPhpVersionIsInstalled.php
- src/Checks/DatabaseCanBeAccessed.php
- src/Checks/Development/ComposerWithDevDependenciesIsUpToDate.php
- src/Checks/Development/ConfigurationIsNotCached.php
- src/Checks/Development/RoutesAreNotCached.php
- src/Checks/DirectoriesHaveCorrectPermissions.php
- src/Checks/EnvFileExists.php
- src/Checks/ExampleEnvironmentVariablesAreSet.php
- src/Checks/MigrationsAreUpToDate.php
- src/Checks/PhpExtensionsAreInstalled.php
- src/Checks/Production/ComposerWithoutDevDependenciesIsUpToDate.php
- src/Checks/Production/ConfigurationIsCached.php
- src/Checks/Production/DebugModeIsNotEnabled.php
- src/Checks/Production/RoutesAreCached.php
- src/Checks/Production/XDebugIsNotEnabled.php
- src/Checks/StorageDirectoryIsLinked.php
- src/SelfDiagnosisCommand.php
- src/SelfDiagnosisServiceProvider.php
- tests/ExampleEnvironmentVariablesAreSetTest.php
- translations/de/checks.php
- translations/de/commands.php
- translations/en/checks.php
- translations/en/commands.php
In reference to #8 I prepared a PR that makes texts translateable. As this is the first time I used translation within a package, I'm not completely convinced I did everything correct, so I would appreciate any reviews. Also, I did not have time to test my changes yet - so please consider it as WIP.
What has been changed:
- Checks and the currently only command do now make use of translations for texts (used `trans()` in favour of `__()`... if that is not good, please tell me).
- Streamlined some texts slightly (removed trailing dot `.` from some command names and removed the `composer.lock` part from the `composer install` checks because the `.lock` file does not necessarily have to exist)
> Make texts translateable

- src/Checks/PhpExtensionsAreInstalled.php
Now that check displays not translated string which is a key to Laravel's trans(...) function because of typo in namespacing.
> Fix typos in check namespace

- README.md
- config/config.php
- src/Checks/LocalesAreInstalled.php
- src/SystemFunctions.php
- tests/ExampleEnvironmentVariablesAreSetTest.php
- tests/LocalesAreInstalledTest.php
- translations/de/checks.php
- translations/en/checks.php
This PR adds a new check called `LocalesAreInstalled` which ensures a list of locales are installed on the operating system by using the output of `locale -a`:
```
$ locale -a
de_AT
de_AT.utf8
en_US
en_US.utf8
```
All possible outcomes of the check are covered by tests. I hope the way I implemented the system call is fine for you.
> Add new check called LocalesAreInstalled

- README.md
- config/config.php
- src/Checks/SupervisorProgramsAreRunning.php
- tests/SupervisorProgramsAreRunningTest.php
- translations/de/checks.php
- translations/en/checks.php
This check ensures that some supervisord programs are running, e.g. horizon. It can also ensure these programs have been restarted recently, i.e. to grab code updates.
It will use `shell_exec` to call `supervisorctl status`:
```
vagrant@dev:~/eval1$ supervisorctl status
horizon                          RUNNING   pid 3004, uptime 0:06:15
horizon2                         STOPPED   Jul 12 07:37 PM
```
This output will be parsed line by line with the help of a regex to identify the individual programs. Also the uptime is parsed to perform an additional check that ensures it is below a certain threshold (or in other words, ensures that the program was recently restarted).
There should be unit tests included for almost every code path.
> Adds a new SupervisorProgramsAreRunning check

- README.md
- config/config.php
- src/Checks/MaintenanceModeNotEnabled.php
- translations/de/checks.php
- translations/en/checks.php
This check ensures the application is not in maintenance mode and reachable for users. The PR does not include any tests because mocking the application is quite hard when you have to override the `app()` helper. But the complexity of the check is rather low anyway.
To be fair, I'm not sure if this check is something you desire. Unlocking the application may actually be something you expect to happen after the self-diagnosis was run successfully. But even if it is something that will always fail during the first run of the self-diagnosis, I kind of like it as it reminds me of something important.
> Adds a new MaintenanceModeNotEnabled check

- README.md
- src/Checks/ComposerWithDevDependenciesIsUpToDate.php
- src/Checks/ComposerWithoutDevDependenciesIsUpToDate.php
This adds only a minor change discussed in #41. It allows for optional arguments to be passed to the composer calls when they check for dependency updates.
> Allows to add additional options to Composer checks

- README.md
- composer.json
- config/config.php
- src/Checks/ServersArePingable.php
- src/Exceptions/InvalidConfigurationException.php
- src/Server.php
- tests/ServersArePingableTest.php
- translations/de/checks.php
- translations/en/checks.php
This check can be used to check firewall rules for example. One usecase would be to ping API servers an application depends on, to make sure they are reachable. The check does not make sure an API itself is online though (i.e. returns valid results).
> Adds a new ServersArePingable check

- src/SystemFunctions.php
I just noticed that there is a logic error in the `SystemFunctions` class which will cause `isFunctionAvailable($func)` to always return false. This PR should fix the issue.
> Fix logic error in SystemFunctions helper class

- README.md
- config/config.php
- src/Checks/ExampleEnvironmentVariablesAreUpToDate.php
- tests/ExampleEnvironmentVariablesAreUpToDateTest.php
- tests/fixtures/.env
- translations/en/checks.php
Adds a new local/development check to ensure that all `.env` variables have been added to `.env.example`. I think this will be useful to make sure that variables I add during development are properly "documented" into the `.env.example`.
The code is nearly identical to the current check that looks for `.env.example` variables that are missing from `.env`. Also, I only added English translations because I don't know German. 😄
> Add local/dev check: ExampleEnvironmentVariablesAreUpToDate

- phpunit.xml.dist
If I run phpunit with the current phpunit.xml.dist I get the next result:
```
Configuration: /var/www/laravel-self-diagnosis/phpunit.xml.dist
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 25:
- Element 'log', attribute 'charset': The attribute 'charset' is not allowed.
- Element 'log', attribute 'yui': The attribute 'yui' is not allowed.
- Element 'log', attribute 'highlight': The attribute 'highlight' is not allowed.
Test results may not be as expected.
```
This pr removes the attributes that are reported as not allowed. If they have a reason to be there, I like to learn it.
> Remove not allowed attributs from phpunit.xml.dist

- src/Checks/RedisCanBeAccessed.php
- tests/RedisCanBeAccessedTest.php
- translations/de/checks.php
- translations/en/checks.php
This is only a small PR that hopefully fixes inconsistent check results of the `RedisCanBeAccessed` check. When I tested the foundation for this test, `Redis::connection($name)`, it seemed to already return a connected connection. But my recent tests do not really confirm this. So I made the check a bit more expressive by explicitely connecting to the redis server.
I also added some additional test cases and additional error messages (also for better testability).
> Fixes RedisCanBeAccessed inconsistent check results

- composer.json
- src/Checks/CorrectPhpVersionIsInstalled.php
- tests/CorrectPhpVersionIsInstalledTest.php
The current check only takes the PHP version from the composer.json file and checks if the current version is the same or higher. But composer has more options, that if used can be conflicted or incorrect tested. See: https://getcomposer.org/doc/articles/versions.md#summary
I have changed the behaviour by using the Semver package from composer to check it.
The only question I have is the change on the getRequiredPhpVersion function. Because it is a public function I didn't want to change it and added a new function getRequiredPhpConstraint. That means that there is now a function that isn't used by the check. If wanted I can mark it as deprecated
> Fix the PHP version check with the use of Semver

- .scrutinizer.yml
- composer.json
I was interested in the scrutinizer status for this project and find out the code coverage didn't work.
I found out that the travis job try to call vendor/bin/ocular but that didn't exist. And I read in https://scrutinizer-ci.com/docs/tools/external-code-coverage/ that the .scrutinizer.yml need some addition. So that are the changes I did in this PR.
> Add ocular for scrutinizer and configure for remote code coverage

- src/Checks/ComposerWithDevDependenciesIsUpToDate.php
- src/Checks/ComposerWithoutDevDependenciesIsUpToDate.php
- src/Checks/CorrectPhpVersionIsInstalled.php
- src/Checks/DatabaseCanBeAccessed.php
- src/Checks/DirectoriesHaveCorrectPermissions.php
- src/Checks/LocalesAreInstalled.php
- src/Checks/PhpExtensionsAreDisabled.php
- src/Checks/PhpExtensionsAreInstalled.php
- src/Checks/RedisCanBeAccessed.php
- src/Checks/ServersArePingable.php
- src/Checks/SupervisorProgramsAreRunning.php
Replaced usage of array_& helpers with Arr::* for Laravel 5.8/9 support.
https://laravel.com/docs/master/upgrade#string-and-array-helpers
> Replace array_* with Arr::* for 5.8 support

- .travis.yml
- composer.json
- src/Checks/ExampleEnvironmentVariablesAreSet.php
- src/Checks/ExampleEnvironmentVariablesAreUpToDate.php
There's an incompatibility with Laravel 5.8 and this because of `vlucas/phpdotenv` between each's composer.json.
| Project                             | Dependency         | Version |
|-------------------------------------|--------------------|---------|
| `laravel/framework`                 | `vlucas/phpdotenv` | ^3.3    |
| `beyondcode/laravel-self-diagnosis` | `vlucas/phpdotenv` | ~2.5    |
I know this PR's current state is not the best way to fix it (unless you want to release a new major version), as it will break backwards compatibility, but here's a first attempt to hopefully help at least get it started. This fixes it for 5.8.
> Upgrade dotenv to v3

- src/Composer.php
In Laravel 5.8, `Composer::getProcess()` now requires the `$command` passed to it as an array.
Also in 5.8, `Composer::findComposer()` now returns an array instead of a string. So I'm using that to determine which `->getProcess()` is called. Should be compatible with 5.7.
Change commit in Laravel: laravel/framework@d1b948103b9933d9881c280df39b289f324bcceb
Fixes #75, ping @kbond
> Update Composer checks to work with Laravel 5.8

- config/config.php
Since the correct locale on macOS is `en_US.UTF-8` and not `en_US.utf8`, the default config should take that into account.
> Add correct locale for macOS. Related to issue #64

- config/config.php
- src/Checks/HorizonIsRunning.php
- tests/HorizonIsRunningTest.php
- translations/en/checks.php
A new command was recently introduced at Horizon: https://github.com/laravel/horizon/blob/3.0/src/Console/StatusCommand.php
The new command tests using this new command instead of checking for supervisor.
In my case i have a container running `horizon` at `foreground` so i don't use supervisor... But this may be useful for other people that runs other process managers instead of supervisor.
This also checks if `horizon` is really `running`, if `horizon` is `paused` the process is still there and supervisor check will succeed, this one will fail.
> Adding Horizon Is Running Check

- src/SelfDiagnosisCommand.php
Currently `php artisan self-diagnosis` totally relies on `APP_ENV`, with this change it will continue to rely on it but now you can run `php artisan self-diagnosis something_else` and this argument will be use for the checks instead of `APP_ENV`.
My use case:
I want to run separate checks on separate servers, like:
```
php artisan self-diagnosis web
php artisan self-diagnosis worker
```
Both servers are `APP_ENV=production`, i just want to run different checks.
But you want still run just based on your `APP_ENV`:
```
php artisan self-diagnosis
```
> Making command environment more flexible

- src/SelfDiagnosisCommand.php
#78 introduced a bug where the environment was always `null` if no environment was passed to the command.
> Fix for default command environment

- composer.json
After release 1.4 I still couldn't install this package on a Laravel 7 project.
It was due to Laravel requiring `vlucas/phpdotenv` in version 4 while, this package required versions `~2.5|~3.3`.
This PR updates that dependency.
While testing, I saw phpdotenv version 3.3 was still pulled, that was due to testbench requiring laravel/framework 5.8. Locally I updated the require-dev dependencies, and tests ran fine. (also needed to update phpunit to 8.5)
I opted for not updating require-dev dependencies in this PR as many changes were required and I don't know if it could break any other thing.
If you want I can send another PR (or add a commit to this one) with updated require-dev dependencies.
> Update composer.json to allow Laravel 7

- src/Checks/ExampleEnvironmentVariablesAreSet.php
- src/Checks/ExampleEnvironmentVariablesAreUpToDate.php
After using the new version on a Laravel 7 app, DotEnv related checks failed due to changes on the DotEnv constructor and static constructors (`::create(...)`)
Reference: https://github.com/vlucas/phpdotenv/blob/v4.0.1/UPGRADING.md#v3-to-v4
This PR update these checks:
- `ExampleEnvironmentVariablesAreSet`
- `ExampleEnvironmentVariablesAreUpToDate`
To comply with the new DotEnv's version.
Note: I added a separated method for DotEnv 4 with a early return to avoid adding to many if branches in each class' `check` method.
> [Laravel 7] fix dotenv 4 checks

- composer.json
- src/Checks/ExampleEnvironmentVariablesAreSet.php
- tests/CorrectPhpVersionIsInstalledTest.php
fix #103 
This PR fix `ExampleEnvironmentVariablesAreSet` for Laravel 8 (dotenv 5) when config is cache.
```bash
➜ php artisan self-diagnosis
|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/12: App key is set...  ✔
Running check 2/12: The correct PHP version is installed...  ✔
Running check 3/12: The database can be accessed...  ✔
Running check 4/12: All directories have the correct permissions...  ✔
Running check 5/12: The environment file exists...  ✔
Running check 6/12: The example environment variables are set...  ✘
Running check 7/12: Required locales are installed...  ✔
Running check 8/12: Maintenance mode is not enabled...  ✔
Running check 9/12: The migrations are up to date...  ✔
Running check 10/12: The required PHP …
```
> Fix dotv5 - Laravel 8 and config cache
